### ISSUE TITLE
class-loader delegate=false ignored by Payara 4.1.2.181

### ISSUE THREAD

**Issue by mkarg** [payara/Payara#4105]
According to https://docs.payara.fish/documentation/payara-server/classloading.html it should be possible to deploy a WAR on Payara 4.1.2.181 which comes with its own v1.1 of JSON-P by adding a glassfish-web.xml disabling classpath delegation. Actually I just tried it out, but in fact the result is that the application still gets provided v1.0 of JSON-P:
```
java.lang.NoSuchMethodError: javax.json.stream.JsonGenerator.writeKey(Ljava/lang/String;)Ljavax/json/stream/JsonGenerator;
```
(That method is marked as @since 1.1, so this is a rather clear proof).

Can somebody confirm that this is a bug in Payara, or tell me what my fault is?

```glassfish-web.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Servlet 3.0//EN" "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">
<glassfish-web-app>
	<class-loader delegate="false" />
</glassfish-web-app>
```

**Comment by smillidge** [comment]
Payara 4.1.2.181 is not maintained in open source. Does this work in the latest 5.x release?

**Comment by mkarg** [comment]
Hi Mike, will check 5.x this week, stay tuned. :-)

**Comment by OndroMih** [comment]
Hi, since no reproducer was provided and we weren't able to reproduce this issue, I'm going to close it. We'll reopen this issue if you provide us an easy to follow reproducer for the latest version of Payara. A reproducer should ideally follow the SSCCE rules: http://www.sscce.org/.

To me, this looks like an issue with the service loader mechanism and should be fixed in 5.194 by #4309.

**Comment by terix2k12** [comment]
I ran into a similar issue as @mkarg (in my case javax.json version 1.0.4 on Payara modules and 1.1.2 inside the WAR) and the `delegate="false"` option is not working.
The reason is probably this hint from the (glassfish) documentation:

> For a number of packages, including java.* and javax.*, symbol resolution is always delegated to the parent class loader regardless of the delegate setting. This prevents applications from overriding core Java runtime classes or changing the API versions of specifications that are part of the Java EE platform.

This does not solve anything, but at least is an explanation.
