### ISSUE TITLE
Mime type not recognized for Javascript files / FISH-1013

### ISSUE THREAD

**Issue by lnegrete30** [payara/Payara#5038]
Loading a Javascript file using the `h:outputScript` tag and setting the target property to `head` results in the following warning in the logs: 

`[#|2020-12-06T03:57:42.882+0000|WARNING|Payara 5.192|javax.enterprise.resource.webcontainer.jsf.context|_ThreadID=29;_ThreadName=http-thread-pool::http-listener-1(5);_TimeMillis=1607227062882;_LevelValue=900;_MessageID=jsf.externalcontext.no.mime.type.found;|
  JSF1091: No mime type could be found for file .  To resolve this, add a mime-type mapping to the applications web.xml.|#]`. The bug seems to be happening due to the file being processed as **empty** in the ExternalContextWrapperImpl used by Faces. This can be debugged using a custom wrapper:

```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.faces.FacesException;
import javax.faces.FacesWrapper;
import javax.faces.context.ExternalContext;
import javax.faces.context.ExternalContextFactory;
import javax.faces.context.ExternalContextWrapper;
import javax.servlet.http.HttpServletRequest;

public class CustomFacesContextFactory extends ExternalContextFactory implements FacesWrapper<ExternalContextFactory>
{
	private static final Logger log = LoggerFactory.getLogger(CustomFacesContextFactory.class);
	
	private ExternalContextFactory factory;
	
	private static final class ExternalContextWrapperImpl extends ExternalContextWrapper
	{
		private ExternalContext externalContext;
		
		public ExternalContextWrapperImpl(ExternalContext externalContext) {
			super();
			this.externalContext = externalContext;
		}
		
		@Override
		public String getMimeType(String file)
		{
                        //Note that file name is coming as empty for JS files 
			log.debug("Getting mime type for file {}", file);
			String mimeType;
			
			if (file != null && file.endsWith(".ecss"))
			{
				mimeType = "text/plain";
			}
			
			else
			{
				mimeType = super.getMimeType(file);
			}
			
			if(Strings.isNullOrEmpty(mimeType))
			{
				HttpServletRequest request = (HttpServletRequest)externalContext.getRequest();
				mimeType = super.getMimeType(FileUtil.getFileNameFromURL(request.getRequestURL().toString()));
			}
			//externalContext.getRequest()
			log.debug("Returning mime type {}", mimeType);
			return mimeType;
		}
		
		@Override
		public ExternalContext getWrapped() {
			return externalContext;
		}
		
		@Override
		public boolean isSecure() {
			return getWrapped().isSecure();
		}
	}
	
	public CustomFacesContextFactory(ExternalContextFactory factory) {
		super();
		this.factory = factory;
	}
	
	@Override
	public ExternalContextFactory getWrapped() {
		return factory;
	}
	
	@Override
	public ExternalContext getExternalContext(Object context, Object request, Object response) throws FacesException {
		ExternalContext externalContext = factory.getExternalContext(context, request, response);
		
		return wrap(externalContext);
	}
	
	private ExternalContext wrap(ExternalContext externalContext) {
		return new ExternalContextWrapperImpl(externalContext);
	}
}
```

**Payara version used: Payara full v5.192**

**Comment by AlanRoth** [comment]
Hi @lnegrete30, 

Would you be able to provide a small sample application that we can deploy quickly and can reproduce this error? It will help use greatly to track down the cause of the issue.

Thank you,
Alan

**Comment by lnegrete30** [comment]
> Hi @lnegrete30,
> 
> Would you be able to provide a small sample application that we can deploy quickly and can reproduce this error? It will help use greatly to track down the cause of the issue.
> 
> Thank you,
> Alan

Thanks for the quick reply Alan, I'll try to setup a reproducer project for this issue.

**Comment by AlanRoth** [comment]
Hi @lnegrete30, do you have any updates on your progress?

**Comment by lnegrete30** [comment]
@AlanRoth I just created this small project to reproduce the issue https://github.com/lnegrete30/ReproducerWeb.git. You only need to trigger an ajax request and check the server logs to notice the mime type mapping warning there

**Comment by AlanRoth** [comment]
Hi @lnegrete30, 

I'm not able to reproduce this issue with 5.2020.7 - nothing related seems to get logged. I have managed to reproduce this issue with 5.192 as originally detailed. Can you try with the latest version of Payara Community? Otherwise, we can assume the issue has been fixed in versions 5.192+.

Thank you.

**Comment by mydeadlyvenoms** [comment]
I still see the issue within my own project using the latest Payara community version (`5.2020.7`).
Therefore, I guess the issue has not been fixed.

**Comment by AlanRoth** [comment]
Hi @lnegrete30 and @mydeadlyvenoms, apologizes for the confusion, I used our docker image to reproduce the issue quickly - which seems to either not log the error or the error does not occur. However, I have been able to reproduce this issue.

**Comment by AlanRoth** [comment]
Hi, 

I have created an internal issue `FISH-1013` to keep track of this. If you are able we always encourage users to contribute to the codebase with a solution to the issue. 

Thank you, 
Alan

**Comment by lnegrete30** [comment]
Thanks @AlanRoth

**Comment by smillidge** [comment]
This is a Mojarra issue rather than a Payara issue. I suggest is raised upstream in the Mojarra Repo https://github.com/eclipse-ee4j/mojarra. The AJAX request still works so it is a spurious log message.

**Comment by AlanRoth** [comment]
Hi, as @smillidge eluded, this is a upstream bug, and upon testing, it seems to still work despite the message.

I will be closing this issue,
Thank you for your understanding,
Alan
