### ISSUE TITLE
Bug Report:  WAR is deployed twice on different context roots 

### ISSUE THREAD

**Issue by rlfnb** [payara/Payara#5367]
# Description #
----------

Packaging a WAR file into payara micro self contained jar deploys the WAR twice.

## Expected Outcome ##

Deploy the WAR once respecting the context root given in the maven plugin configuration and/or taking care to the glassfish-web.xml (context-root).

## Current Outcome ##

`[2021-08-03T21:37:32.747+0200] [] [INFO] [] [PayaraMicro] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1628019452747] [levelValue: 800] [[
  
{
    "Instance Configuration": {
        "Host": "fe80:0:0:0:787a:eeff:fe3d:bc44%veth2473960",
        "Http Port(s)": "8080",
        "Https Port(s)": "",
        "Instance Name": "Outstanding-Goby",
        "Instance Group": "MicroShoal",
        "Hazelcast Member UUID": "b5f5b3c3-451f-4076-86a5-321a3d71c2f7",
        "Deployed": [
            {
                "Name": "RepCaseRedundantDeploy-1.0-SNAPSHOT",
                "Type": "war",
                "Context Root": "/RepCaseRedundantDeploy-1.0-SNAPSHOT"
            },
            {
                "Name": "ROOT",
                "Type": "war",
                "Context Root": "/"
            }
        ]
    }
}]]
`

## Steps to reproduce ## 

[RepCaseRedundantDeploy.zip](https://github.com/payara/Payara/files/6926668/RepCaseRedundantDeploy.zip)

Unzip the archive, change directory,  run mvn install payara-micro:bundle and then start java -jar  target/RepCaseRedundantDeploy-1.0-SNAPSHOT-microbundle.jar

curl localhost:8080/ returns the same as localhost:8080/RepCaseRedundantDeploy-1.0-SNAPSHOT/

The maven project is also suitable to reproduce #5363 (just change the version being used in the payara-micro plugin to use 5.2021.5.

## Environment ##

- **Distribution**: Micro
- **JDK Version**:  11- OpenJDK
- **Operating System**: Linux

**Comment by shub8968** [comment]
Hi @rlfnb,

Kindly use `<autoDeployEmptyContextRoot>false</autoDeployEmptyContextRoot>`  configuration tag for Uber Jar Creation. Kindly refer to the documentation on it - https://docs.payara.fish/community/docs/documentation/ecosystem/maven-plugin.html#_configurable_goals.
#5363 has been addressed already.

**Comment by rlfnb** [comment]
TBH, its not solved, you are right its not longer deployed twice. But the tipping point:

its not deployed on the context root as specified in the pom.xml / payara-micro-maven-plugin configuration.

`Payara Micro URLs:
http://192.168.100.26:8080/RepCaseRedundantDeploy-1.0-SNAPSHOT
`

**Comment by shub8968** [comment]
Hi @rlfnb,

I was about to reopen the issue but opened a fresh one.

**Comment by shub8968** [comment]
Duplicate of #5383
